project_id = "daqqfhamsdjrhsbwnkll"

[functions.generate-chatbot-token]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = false

[functions.salesflow-chat]
verify_jwt = false

[functions.salesflow-broker-api]
verify_jwt = false

[functions.send-notification]
verify_jwt = false
